export default [
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 0,
    id: 2161,
    isAssociatResource: null,
    sectionId: 1,
    level: 1,
    lessonId: 1,
    name: "81建军节的礼物二级目录",
    path: "/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 0,
    id: 2016,
    isAssociatResource: null,
    sectionId: 1,
    level: 1,
    lessonId: 1,
    name: "1 第一章",
    path: "/",
    seq: 1,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 0,
    id: 2022,
    isAssociatResource: null,
    sectionId: 1,
    level: 1,
    lessonId: 1,
    name: "2 第二章",
    path: "/",
    seq: 2,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 0,
    id: 2033,
    isAssociatResource: null,
    sectionId: 1,
    level: 1,
    lessonId: 1,
    name: "3 第三章",
    path: "/",
    seq: 3,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 0,
    id: 2117,
    isAssociatResource: null,
    sectionId: 1,
    level: 1,
    lessonId: 1,
    name: "4 第四章",
    path: "/",
    seq: 4,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 0,
    id: 2127,
    isAssociatResource: null,
    sectionId: 1,
    level: 1,
    lessonId: 1,
    name: "总结",
    path: "/",
    seq: 5,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 0,
    id: 2168,
    isAssociatResource: null,
    sectionId: 1,
    level: 1,
    lessonId: 1,
    name: "81建军节的礼物三级目录（3级）",
    path: "/",
    seq: 6,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 0,
    id: 2198,
    isAssociatResource: null,
    sectionId: 1,
    level: 1,
    lessonId: 1,
    name: "84周六二级目录之第二（2级）",
    path: "/",
    seq: 7,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 0,
    id: 2185,
    isAssociatResource: null,
    sectionId: 1,
    level: 1,
    lessonId: 1,
    name: "83是周五一级目录（1级）",
    path: "/",
    seq: 8,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 0,
    id: 2203,
    isAssociatResource: null,
    sectionId: 1,
    level: 1,
    lessonId: 1,
    name: "教材+1",
    path: "/",
    seq: 9,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 0,
    id: 2503,
    isAssociatResource: null,
    sectionId: 1,
    level: 1,
    lessonId: 1,
    name: "1",
    path: "/",
    seq: 10,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 0,
    id: 2510,
    isAssociatResource: null,
    sectionId: 1,
    level: 1,
    lessonId: 1,
    name: "第一",
    path: "/",
    seq: 11,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2016,
    id: 2019,
    isAssociatResource: null,
    sectionId: 1,
    level: 2,
    lessonId: 1,
    name: "1-2 第二课",
    path: "/2016/",
    seq: 1,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2016,
    id: 2017,
    isAssociatResource: null,
    sectionId: 1,
    level: 2,
    lessonId: 1,
    name: "1-3 第三课 春天来了，大地苏醒，花开虫儿飞舞",
    path: "/2016/",
    seq: 2,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 1,
    bookId: 887,
    pid: 2016,
    id: 2018,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name:
      "1-1 第一课 冬天来了，草木枯黄，树叶随风飘落，只留下光秃秃的树枝挺立风中，与严寒抵抗。从树枝中间，偶尔可以看到挂在树杈中的鸟巢，鸟儿也离窝而转去温暖的南方，待到明年春天来临，它们又会重新回归到你鸟巢中，带着新生的生命。",
    path: "/2016/2017/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 1,
    bookId: 887,
    pid: 2019,
    id: 2020,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "1-2-1 第一节 春天来了",
    path: "/2016/2019/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 1,
    bookId: 887,
    pid: 2019,
    id: 2021,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "1-2-1 第二节",
    path: "/2016/2019/",
    seq: 1,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2019,
    id: 2476,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "1-2-1 第三节 小桥流水人家，古道西风瘦马",
    path: "/2016/2019/",
    seq: 2,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2034,
    id: 2025,
    isAssociatResource: null,
    sectionId: 1,
    level: 2,
    lessonId: 1,
    name: "4-2-1 第一节",
    path: "/2022/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2022,
    id: 2037,
    isAssociatResource: null,
    sectionId: 1,
    level: 2,
    lessonId: 1,
    name: "2-1 第一课",
    path: "/2022/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2022,
    id: 2027,
    isAssociatResource: null,
    sectionId: 1,
    level: 2,
    lessonId: 1,
    name: "2-2 第二课",
    path: "/2022/",
    seq: 1,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2022,
    id: 2030,
    isAssociatResource: null,
    sectionId: 1,
    level: 2,
    lessonId: 1,
    name: "2-3 第三课",
    path: "/2022/",
    seq: 2,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 1,
    bookId: 887,
    pid: 2027,
    id: 2029,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "2-2-1  第一节",
    path: "/2022/2027/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2027,
    id: 2028,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "2-2-3  第三节《春晓》这首小诗，初读似觉平淡无奇，反复读之",
    path: "/2022/2027/",
    seq: 2,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2027,
    id: 2038,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "2-2-4   第四节",
    path: "/2022/2027/",
    seq: 3,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2030,
    id: 2031,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "2-3-1 第一节",
    path: "/2022/2030/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 1,
    bookId: 887,
    pid: 2027,
    id: 2039,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "2-2-2  第二节",
    path: "/2022/2037/",
    seq: 1,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 1,
    bookId: 887,
    pid: 2033,
    id: 2024,
    isAssociatResource: null,
    sectionId: 1,
    level: 2,
    lessonId: 1,
    name: "3-1  第一节",
    path: "/2033/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2117,
    id: 2034,
    isAssociatResource: null,
    sectionId: 1,
    level: 2,
    lessonId: 1,
    name: "4-2 第二课",
    path: "/2117/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2117,
    id: 2118,
    isAssociatResource: null,
    sectionId: 1,
    level: 2,
    lessonId: 1,
    name: "4-1 第一课",
    path: "/2117/",
    seq: 1,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2117,
    id: 2119,
    isAssociatResource: null,
    sectionId: 1,
    level: 2,
    lessonId: 1,
    name: "4-3 第三课",
    path: "/2117/",
    seq: 2,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2034,
    id: 2035,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "4-2-2 第三节",
    path: "/2117/2034/",
    seq: 1,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2034,
    id: 2036,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "4-2-3 第二节",
    path: "/2117/2034/",
    seq: 2,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 1,
    bookId: 887,
    pid: 2118,
    id: 2121,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "4-1-1 第一小节",
    path: "/2117/2118/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2118,
    id: 2122,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "4-1-2  第二小节",
    path: "/2117/2118/",
    seq: 1,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2118,
    id: 2123,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "4-1-3 第三小节",
    path: "/2117/2118/",
    seq: 2,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2119,
    id: 2124,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "4-3-1 第一小节",
    path: "/2117/2119/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2119,
    id: 2125,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "4-3-2 第二小节",
    path: "/2117/2119/",
    seq: 1,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2119,
    id: 2126,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "4-3-3 第三小节",
    path: "/2117/2119/",
    seq: 2,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2127,
    id: 2128,
    isAssociatResource: null,
    sectionId: 1,
    level: 2,
    lessonId: 1,
    name: "小节一",
    path: "/2127/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2127,
    id: 2129,
    isAssociatResource: null,
    sectionId: 1,
    level: 2,
    lessonId: 1,
    name: "小节二",
    path: "/2127/",
    seq: 1,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 1,
    bookId: 887,
    pid: 2161,
    id: 2174,
    isAssociatResource: null,
    sectionId: 1,
    level: 2,
    lessonId: 1,
    name: "81建军节的礼物二级目录之第二级（2级）",
    path: "/2161/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2168,
    id: 2169,
    isAssociatResource: null,
    sectionId: 1,
    level: 2,
    lessonId: 1,
    name: "81建军节的礼物三级目录之第二级（3级）",
    path: "/2168/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2169,
    id: 2170,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "81建军节的礼物三级目录之第三级（3级）",
    path: "/2168/2169/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 1,
    bookId: 887,
    pid: 2203,
    id: 2204,
    isAssociatResource: null,
    sectionId: 1,
    level: 2,
    lessonId: 1,
    name: "教材+2",
    path: "/2203/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2503,
    id: 2504,
    isAssociatResource: null,
    sectionId: 1,
    level: 2,
    lessonId: 1,
    name: "2",
    path: "/2503/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2504,
    id: 2505,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "3",
    path: "/2503/2504/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2510,
    id: 2511,
    isAssociatResource: null,
    sectionId: 1,
    level: 2,
    lessonId: 1,
    name: "第二",
    path: "/2510/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
  {
    permissionStatus: null,
    topicStatus: 0,
    bookId: 887,
    pid: 2511,
    id: 2512,
    isAssociatResource: null,
    sectionId: 1,
    level: 3,
    lessonId: 1,
    name: "第三",
    path: "/2510/2511/",
    seq: 0,
    versionId: 128,
    isCanMove: null,
  },
];
